attempt at fixing debian11

diff --git a/kvm-install-vm b/kvm-install-vm
--- a/kvm-install-vm
+++ b/kvm-install-vm
@@ -506,16 +506,21 @@ _EOF_
     qemu-img create -q -f qcow2 -F qcow2 -b $IMAGE $DISK && ok
     if $RESIZE_DISK
     then
-        case "${DISTRO}" in
-            debian11 )  ROOT_PARTITION=/dev/sda15;;
-            *)          ROOT_PARTITION=/dev/sda2;;
-        esac
         outputn "Resizing the disk to $DISK_SIZE"
-        qemu-img create -f qcow2 \
-            -o preallocation=metadata $DISK.new $DISK_SIZE &>> ${VMNAME}.log \
-            && virt-resize --quiet --expand ${ROOT_PARTITION} $DISK $DISK.new &>> ${VMNAME}.log \
-            && (mv $DISK.new $DISK && ok) \
-            || die "Could not resize disk."
+        case "${DISTRO}" in
+            debian11 )
+                qemu-img resize $DISK $DISK_SIZE &>> ${VMNAME}.log \
+                    && ok \
+                    || die "Could not resize disk."
+                ;;
+            *)
+                qemu-img create -f qcow2 \
+                    -o preallocation=metadata $DISK.new $DISK_SIZE &>> ${VMNAME}.log \
+                    && virt-resize --quiet --expand ${ROOT_PARTITION} $DISK $DISK.new &>> ${VMNAME}.log \
+                    && (mv $DISK.new $DISK && ok) \
+                    || die "Could not resize disk."
+                ;;                
+        esac
     fi
 
     # Create CD-ROM ISO with cloud-init config
