hopefully fix resize disk for all

diff --git a/kvm-install-vm b/kvm-install-vm
--- a/kvm-install-vm
+++ b/kvm-install-vm
@@ -512,20 +512,7 @@ _EOF_
     if $RESIZE_DISK
     then
         outputn "Resizing the disk to $DISK_SIZE"
-        case "${DISTRO}" in
-            debian1*)
-                qemu-img resize $DISK $DISK_SIZE &>> ${VMNAME}.log \
-                    && ok \
-                    || die "Could not resize disk."
-                ;;
-            *)
-                qemu-img create -f qcow2 \
-                    -o preallocation=metadata $DISK.new $DISK_SIZE &>> ${VMNAME}.log \
-                    && virt-resize --quiet --expand ${ROOT_PARTITION} $DISK $DISK.new &>> ${VMNAME}.log \
-                    && (mv $DISK.new $DISK && ok) \
-                    || die "Could not resize disk."
-                ;;                
-        esac
+        qemu-img resize $DISK $DISK_SIZE &>> ${VMNAME}.log && ok || die "Could not resize disk."
     fi
 
     # Create CD-ROM ISO with cloud-init config
